### ISSUE TITLE
Grammatical mistakes

### ISSUE THREAD

**Issue by MysteryDash** [jelle619/openlicenseformodification#1]
Hello,  
I'd like to say that I'm happy my SNCL inspired you to create your own license. Creating a huge amount of licenses is definitely not a solution to the confusion people may already have with the existing licenses, but I believe there is a lack of license with personal use/restricted commercial use in the open-source world.  
I corrected some grammatical mistakes in the latest version of the SNCL that are still present in your text, so you might want to check that out.  
Also, there is one thing that bugs me with clause 1.2: "This means that it must contain significant changes". This, in my opinion, explicitely forbids forks with corrected grammatical/spelling mistakes (this is just an example, it could prevent other small modifications from being done).

**Comment by jelle619** [comment]
Hmmm, interesting. Thank you for your suggestion! I'll check whether there's anything I can do to improve the license.

Again, thanks a lot!

**Comment by jelle619** [comment]
I have also added a 'special thanks' section to the readme with a link to your license. Of course, it would only be fair to mention where you can find the source material.

**Comment by MysteryDash** [comment]
Thanks, I appreciate it.

**Comment by jelle619** [comment]
As there don't seem to be any further issues, I will now close this issue. If you have any more questions, issues or suggestions, please let me know!
